/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.nsenave.sandbox.github.packages;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
